baseURL: "https://arjunsubedi.site"
languageCode: en-us
title: Arjun Subedi
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    # - identifier: experience
    #   name: Experience
    #   url: /experience
    #   weight: 40
    # - identifier: search
    #   name: Search
    #   url: /search
    #   weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Arjun Subedi"
    subtitle: Hey there! 🚀 I'm a software engineer with a zest for designing and developing full-stack web applications using industry best practices. 
          💡 Currently, I'm working as a Software Eningeer at the BT Group. I thrive on tackling complex challenges with innovative solutions. When I'm not busy coding away, you might find me strumming some groovy tunes on my guitar 🎸 (I promise, I'm better at coding!).
    imageUrl: "/home/formal-pic-small.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:arjunsubedi@live.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/arjunsubedi79"
    - name: "github"
      url: "https://github.com/arjuntheguru"


  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
